IRecordweb/Controllers/DematMasterController.cs
using BAL;
using IRecordweb.Models;
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace IRecordweb.Controllers
{
    public class DematMasterController : Controller
    {

        string URL = ConfigurationManager.AppSettings["ScreenURL"];
        string BasicAuth = ConfigurationManager.AppSettings["Authorization"];
        // GET: DematMaster
        public ActionResult Index()
        {
            //DataTable dtfin = Session["Dt_FinancialYear"] as DataTable;//Member Details(MemberId,FinancialYearUserID)
            //var MemberCode = dtfin.Rows[0]["MemberId"].ToString();
            //var FinancialYearCode = dtfin.Rows[0]["FinancialYearUserID"].ToString();
            //var CreatedById = Session["UserID"].ToString();

            //var ID = Session["UserID"];
            //System.Net.ServicePointManager.SecurityProtocol =SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;System.Net.ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };
            //var client = new RestClient(URL + "api/Master/DEMATMASTER?DBAction=ViewByUserId&ID=" + MemberCode + ':' + FinancialYearCode);
            //client.Timeout = -1;
            //var request = new RestRequest(Method.POST);
            //request.AddHeader("Authorization", BasicAuth);
            //request.AddHeader("Content-Type", "application/json");
            //IRestResponse response = client.Execute(request);
            //Console.WriteLine(response.Content);
            //DataSet data = JsonConvert.DeserializeObject<DataSet>(response.Content);
            //List<DEMAT> list = new List<DEMAT>();
            //foreach (DataRow dr in data.Tables[0].Rows)
            //{
            //    DEMAT item = new DEMAT();
            //    item.DematID = Convert.ToInt32(dr["DematID"].ToString());
            //    item.Code = dr["Code"].ToString();
            //    item.Name = dr["Name"].ToString();
            //    item.Active = Convert.ToBoolean(dr["Active"].ToString());
            //    item.CreatedDate = Convert.ToDateTime(dr["CreatedDate"].ToString());
            //    list.Add(item);
            //}
            //DEMAT _demat = new DEMAT();
            //_demat.ShowDemat = list;
            return View();
        }
        [HttpGet]
        public ActionResult SaveDemat()
        {

            ViewBag.DemateList = GetAllDemate();
            return View();
        }
        public static object DataTableToJSON(System.Data.DataTable table)
        {
            var list = new List<Dictionary<string, object>>();

            foreach (DataRow row in table.Rows)
            {
                var dict = new Dictionary<string, object>();

                foreach (DataColumn col in table.Columns)
                {
                    dict[col.ColumnName] = (Convert.ToString(row[col]));
                }
                list.Add(dict);
            }
            JavaScriptSerializer serializer = new JavaScriptSerializer();

            return serializer.Serialize(list);
        }
        public JsonResult GetListofDemat()
        {

            DataTable dtfin = Session["Dt_FinancialYear"] as DataTable;//Member Details(MemberId,FinancialYearUserID)
            var MemberCode = dtfin.Rows[0]["MemberId"].ToString();
            var FinancialYearCode = dtfin.Rows[0]["FinancialYearUserID"].ToString();
            var CreatedById = Session["UserID"].ToString();

            String strConnString = ConfigurationManager.ConnectionStrings["IrecordwebConnection"].ConnectionString;
            SqlConnection con = new SqlConnection(strConnString);
            SqlCommand cmd = new SqlCommand();

            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "[DBO].[SP_DEMATDATA]";
            cmd.Parameters.Add("@ACTION", SqlDbType.NVarChar).Value = "VIEWBYUSERID";
            cmd.Parameters.Add("@CreatedBy", SqlDbType.Int).Value = MemberCode;
            cmd.Parameters.Add("@DematId", SqlDbType.Int).Value = FinancialYearCode;

            cmd.Connection = con;
            System.Data.DataTable DT = new System.Data.DataTable();
            try
            {
                con.Open();

                using (var da = new SqlDataAdapter(cmd))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    da.Fill(DT);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                con.Close();
                con.Dispose();
            }
            return Json(DataTableToJSON(DT), JsonRequestBehavior.AllowGet);

        }
        public IEnumerable<SelectListItem> GetAllDemate()
        {
            DataTable dtfin = Session["Dt_FinancialYear"] as DataTable;//Member Details(MemberId,FinancialYearUserID)
            var MemberCode = dtfin.Rows[0]["MemberId"].ToString();
            var FinancialYearCode = dtfin.Rows[0]["FinancialYearUserID"].ToString();
            var CreatedById = Session["UserID"].ToString();
            string strConnString = ConfigurationManager.ConnectionStrings["IrecordwebConnection"].ConnectionString;
            DataTable DT = new DataTable();
            SqlConnection con = new SqlConnection(strConnString);
            SqlCommand cmd = new SqlCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "[dbo].[SP_DEMATDATA]";
            cmd.Parameters.Add("@Action", SqlDbType.NVarChar).Value = "VIEW_ADMIN_DEMATE_DATA";
            cmd.Parameters.Add("@Memberid", SqlDbType.Int).Value = MemberCode;
            
            //cmd.Parameters.Add("@Var1", SqlDbType.NVarChar).Value = username;

            cmd.Connection = con;

            try
            {
                con.Open();
                /////Only Use Case Of Mapping
                //string query = cmd.CommandText;
                //foreach (SqlParameter p in cmd.Parameters)
                //{
                //    query += " "+p.ParameterName+"="+p.Value.ToString()+"\n";
                //}
                using (var da = new SqlDataAdapter(cmd))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    da.Fill(DT);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                con.Close();
                con.Dispose();
            }
            SelectList lstobj = null;

            try
            {
                List<SelectListItem> mylist = new List<SelectListItem>();
                foreach (DataRow dr in DT.Rows)
                {
                    SelectListItem Slist = new SelectListItem();
                    Slist.Text = dr["NAME"].ToString();
                    Slist.Value = dr["ID"].ToString();
                    mylist.Add(Slist);
                }
                // Loading.  


                // Setting.  
                lstobj = new SelectList(mylist, "Value", "Text");
            }
            catch (Exception ex)
            {
                // Info  
                throw ex;
            }

            // info.  
            return lstobj;




        }


        [HttpPost]
        public ActionResult SaveDemat(DEMAT _Demat)
        {
            if (ModelState.IsValid)
            {
                foreach (int DEMATEID in _Demat.SelectedMultiDemate)
                {


                    DataTable dtfin = Session["Dt_FinancialYear"] as DataTable;//Member Details(MemberId,FinancialYearUserID)
                    var MemberCode = dtfin.Rows[0]["MemberId"].ToString();
                    var FinancialYearCode = dtfin.Rows[0]["FinancialYearUserID"].ToString();
                    var CreatedById = Session["UserID"].ToString();

                    DEMAT objdata = new DEMAT();
                    objdata.DematID = DEMATEID;
                    objdata.MemberId = Convert.ToInt32(MemberCode.ToString());
                    objdata.FinancialYearMemberID = Convert.ToInt32(FinancialYearCode.ToString());
                    objdata.Name = DEMATEID.ToString();
                    objdata.Active = _Demat.Active;
                    objdata.CreatedBy = Convert.ToInt32(CreatedById.ToString());
                    var json = new JavaScriptSerializer().Serialize(objdata);
                    System.Net.ServicePointManager.SecurityProtocol =SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;System.Net.ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };
                    var client = new RestClient(URL + "api/Master/DEMATMASTER?DBAction=Insert&ID=0");
                    client.Timeout = -1;
                    var request = new RestRequest(Method.POST);
                    request.AddHeader("Authorization", BasicAuth);
                    request.AddHeader("Content-Type", "application/json");
                    request.AddParameter("application/json", json.ToString(), ParameterType.RequestBody);
                    IRestResponse response = client.Execute(request);
                    Console.WriteLine(response.Content);
                    DataSet data = JsonConvert.DeserializeObject<DataSet>(response.Content);
                    foreach (DataRow dr in data.Tables[0].Rows)
                    {
                        DEMAT item = new DEMAT();
                        item.Code = dr["Code"].ToString();
                        item.Message = dr["Message"].ToString();
                        if (item.Code == "200")
                        {
                            ViewBag.Message = item.Message;
                            TempData["Message"] = item.Message;

IRecordweb/Views/DematMaster/DeleteDemat.cshtml
@model IRecordweb.Models.DEMAT

@{
    ViewBag.Title = "DeleteDemat";
}
<div class="display_adds_parent">
    <div class="display_adds_view_box">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h1 class="mb-0">Demat Master</h1>

            <div class="page-title-right">
                @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-dark" })
            </div>

        </div>
    </div>
    @{
        bool status = Model.Active;
        string Active = status == true ? "Active" : "Inanctive";
    }
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="card">
            <div class="card-body">
                <div class="row form_2 view_mode">

                    <div class="col-sm-12 col-md-6 mb-3 d-flex">
                        <label class="mb-0">@Html.DisplayNameFor(model => model.Name)</label>
                        <span class="form-control">@Html.DisplayFor(model => model.Name)</span>
                    </div>

                    <div class="col-sm-12 col-md-6 mb-3 d-flex">
                        <label class="mb-0">@Html.DisplayNameFor(model => model.Active)</label>
                        <span class="form-control">@Html.DisplayFor(model => Active)</span>
                    </div>

                    <div class="col-sm-12 col-md-6 mb-3 d-flex">
                        <label class="mb-0">@Html.DisplayNameFor(model => model.CreatedDate)</label>
                        <span class="form-control">@Html.DisplayFor(model => model.CreatedDate)</span>
                    </div>

                    <div class="col-sm-12 text-center mt-3">
                        <input type="submit" value="Delete" class="btn btn-danger" /> @*data-bs-target="#myModal" data-bs-toggle="modal"*@
                    </div>
                    @*}*@
                </div>
            </div>
        </div>

            <div class="modal fade" id="myModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-md">
                    <div class="modal-content">

                        <!-- Modal Header -->
                        <div class="modal-header">
                            <h4 class="modal-title">Delete Demat </h4>
                            <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                        </div>

                        <!-- Modal body -->
                        <div class="modal-body">
                            Are you sure you want to delete this?
                        </div>

                        <!-- Modal footer -->
                        <div class="modal-footer">
                            <input type="submit" value="OK" class="btn btn-danger" />
                            <button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button>
                        </div>
                    </div>
                </div>
            </div>
    }
    </div>
    <div class="display_adds display_adds_right text-center">
        <div class="mobile_adds mb-3">
            <img src="https://via.placeholder.com/970x90.png/007BFF/FFFFFF?text=Irecord+Ads" alt="" />
        </div>
        <div class="desktop_adds">
            <img src="https://via.placeholder.com/160x601.png/007BFF/FFFFFF?text=Irecord+Ads" alt="" />
        </div>
    </div>
</div>

IRecordweb/Views/DematMaster/DetailsDemat.cshtml
@model IRecordweb.Models.DEMAT

@{
    ViewBag.Title = "DetailsDemat";
}

<style>
    .isdisabled {
        color: currentColor;
        cursor: not-allowed;
        opacity: 0.5;
        text-decoration: none;
        pointer-events: none;
    }
</style>

<div class="display_adds_parent">
    <div class="display_adds_view_box">

        <div class="col-12">
            <div class="page-title-box d-flex align-items-center justify-content-between">
                <h1 class="mb-0">Demat Master</h1>

                <div class="page-title-right">
                    @*@if (Session["RoleId"] != null)
                        {
                        if (Session["RoleName"].ToString() == "ADMIN" || Session["RoleName"].ToString() == "ACCOUNTANT" || Session["RoleName"].ToString() == "INVESTOR" || Session["RoleName"].ToString() == "MEMBER" || Session["RoleName"].ToString() == "ADVISOR")
                            {
                            @Html.ActionLink("Edit", "EditDemat", new { id = Model.DematID }, new { @class = "btn btn-primary" })
                            }
                        else
                            {
                            @Html.ActionLink("Edit", "EditDemat", new { id = Model.DematID }, new { @class = "isdisabled btn btn-primary" })
                            }
                        }*@
                    @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-dark ml-1" })
                </div>

            </div>
        </div>
        @{
            bool status = Model.Active;
            string Active = status == true ? "Active" : "Inanctive";
        }

        <div class="card">
            <div class="card-body">
                <div class="row form_2 view_mode">
                    <div class="col-sm-12 col-md-6 mb-3 d-flex">
                        <label class="mb-0">@Html.DisplayNameFor(model => model.Name)</label>
                        <span class="form-control">@Html.DisplayFor(model => model.Name)</span>
                    </div>

                    <div class="col-sm-12 col-md-6 mb-3 d-flex">
                        <label class="mb-0">@Html.DisplayNameFor(model => model.Active)</label>
                        <span class="form-control">@Html.DisplayFor(model => Active)</span>
                    </div>

                    <div class="col-sm-12 col-md-6 mb-3 d-flex">
                        <label class="mb-0">@Html.DisplayNameFor(model => model.CreatedDate)</label>
                        <span class="form-control">@Html.DisplayFor(model => model.CreatedDate)</span>
                    </div>

                </div>
            </div>
        </div>

    </div>
    <div class="display_adds display_adds_right text-center">
        <div class="mobile_adds mb-3">
            <img src="https://via.placeholder.com/970x90.png/007BFF/FFFFFF?text=Irecord+Ads" alt="" />
        </div>
        <div class="desktop_adds">
            <img src="https://via.placeholder.com/160x601.png/007BFF/FFFFFF?text=Irecord+Ads" alt="" />
        </div>
    </div>
</div>

IRecordweb/Views/DematMaster/EditDemat.cshtml
@model IRecordweb.Models.DEMAT

@{
    ViewBag.Title = "EditDemat";
}

<div class="display_adds_parent">
    <div class="display_adds_view_box">

        <div class="col-12">
            <div class="page-title-box d-flex align-items-center justify-content-between">
                <h1 class="mb-0">Demat Master</h1>

                <div class="page-title-right">
                    @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-dark" })
                </div>

            </div>
        </div>


        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="card">
                <div class="card-body">
                    <div class="row form_2">

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.DematID)

                        <div class="col-sm-12 col-md-6 mb-3 d-flex">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="w-100">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @disabled= "disabled" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="col-sm-12 col-md-6 mb-3 d-flex">
                            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="w-10">
                                <div class="checkbox">
                                    @Html.EditorFor(model => model.Active)
                                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-12 text-center mt-3">
                            <input type="submit" value="Update" class="btn btn-primary" />  @*data-bs-target="#myModal" data-bs-toggle="modal"*@
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="myModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-md">
                    <div class="modal-content">

                        <!-- Modal Header -->
                        <div class="modal-header">
                            <h4 class="modal-title">Update Demat Master </h4>
                            <div class="btn-close" data-bs-dismiss="modal"></div>
                        </div>

                        <!-- Modal body -->
                        <div class="modal-body">
                            Record Updated Successfully..!
                        </div>

                        <!-- Modal footer -->
                        <div class="modal-footer">
                            <input type="submit" value="OK" name="OK" class="btn btn-danger">
                            <button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button>
                        </div>

                    </div>
                </div>
            </div>
            }

    </div>
    <div class="display_adds display_adds_right text-center">
        <div class="mobile_adds mb-3">
            <img src="https://via.placeholder.com/970x90.png/007BFF/FFFFFF?text=Irecord+Ads" alt="" />
        </div>
        <div class="desktop_adds">
            <img src="https://via.placeholder.com/160x601.png/007BFF/FFFFFF?text=Irecord+Ads" alt="" />
        </div>
    </div>
</div>

@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

IRecordweb/Views/DematMaster/Index.cshtml
@model IRecordweb.Models.DEMAT

@{
    ViewBag.Title = "Index";
}

<style>
    .isdisabled {
        color: currentColor;
        cursor: not-allowed;
        opacity: 0.5;
        text-decoration: none;
        pointer-events: none;
    }


    /* li.pagination-page.ng-scope {
        MARGIN-LEFT: 15PX;
        MARGIN-RIGHT: 15PX;
    }

    .MYPAGECSS {
        BORDER: 1PX SOLID !important;
        FLOAT: RIGHT !important;
        BORDER-RADIUS: 5PX !important;
    }

    li.pagination-page.ng-scope.active {
        FONT-WEIGHT: BOLD;
    } */
</style>

@*--------*Angular JS* SECTION------*@

<script src="~/AngScripts/angular.js"></script>
<script src="~/AngScripts/ngStorage.min.js"></script>
<script src="//angular-ui.github.io/bootstrap/ui-bootstrap-tpls-1.0.3.js"></script>
@*---------*Angular JS* SECTION-----*@

<link href="~/css/style.css" rel="stylesheet" />
<div class="display_adds display_adds_top text-center mb-3">
    <img src="https://via.placeholder.com/970x90.png/007BFF/FFFFFF?text=Irecord+Ads" alt="" />
</div>

<div class="col-12">
    <div class="page-title-box d-flex align-items-center justify-content-between">
        <h1 class="mb-0">Demat Master</h1>

        <div class="page-title-right">
            @*@if (Session["RoleId"] != null)
                {
                if (Session["RoleName"].ToString() == "ADMIN" || Session["RoleName"].ToString() == "CA" || Session["RoleName"].ToString() == "ACCOUNTANT" || Session["RoleName"].ToString() == "INVESTOR" || Session["RoleName"].ToString() == "ADVISOR")
                    {*@
            <input type="submit" class="btn btn-primary add-on" value="Add Demat" onclick="location.href='@Url.Action("SaveDemat", "DematMaster")'" />
            @*}
                else
                    {*@
            @*<input type="submit" class="btn btn-primary add-on" value="Add Account" onclick="location.href='@Url.Action("SaveDemat", "DematMaster")'" />*@
            @*}
                }*@
        </div>

    </div>
</div>
<div ng-app="myApp" ng-controller="myctrn" ng-init="PageLoad()" id="" class="">
    <div class="card">
        <div class="card-body">
            <div class="pagination_box w-100 mb-3 d-sm-flex justify-content-end">
                <div class="float-sm-end">
                    <uib-pagination class="pagination MYPAGECSS" total-items="Info.length" ng-model="page"
                                    ng-change="pageChanged()" previous-text="&lsaquo;" next-text="&rsaquo;" items-per-page=10></uib-pagination>
                </div>
            </div>
            <div class="table-responsive">
                <table id="mytable" class="table table-hover table-bordered mb-0">
                    <thead class="table-light">
                        <tr>
                            <th>#</th>
                            <th>Name <input type="text" class="form-control " ng-model="search.Name" placeholder="Demat Name"></th>
                            <th>Code <input type="text" class="form-control " ng-model="search.Code" placeholder="Code"></th>
                            <th>Active <input type="text" class="form-control " ng-model="search.Active" placeholder="Active"></th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tr>
                    <tr ng-repeat="data in Info | filter:search | limitTo:10:10*(page-1)">
                        <td>{{$index+1}}</td>
                        <td>{{data.Name}}</td>
                        <td>{{data.Code}}</td>
                        <td>{{data.Active}}</td>

                        <td class="whitespace_nowrap">
                            <ul class="list-inline mb-0">
                                <li class="list-inline-item">
                                    <a href="/DematMaster/DetailsDemat?Id={{data.DematID}}" class="px-2 btn btn-outline-primary"><i class="las la-search font-size-18"></i></a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="/DematMaster/EditDemat?Id={{data.DematID}}&&Status=Edit" class="px-2 btn btn-outline-primary"><i class="las la-pencil-alt font-size-18"></i></a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="/DematMaster/DeleteDemat?Id={{data.DematID}}&&Status=Delete" class="px-2 btn btn-outline-danger"><i class="las la-trash-alt font-size-18"></i></a>
                                </li>
                            </ul>
                        </td>
                    </tr>


                </table>
            </div>

        </div>
    </div>
</div>
<script type="text/javascript" charset="utf8" src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.2.min.js"></script>
<script type="text/javascript" charset="utf8" src="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/jquery.dataTables.min.js"></script>
<script>
    function loaddt() {


        $.noConflict();
        jQuery(document).ready(function ($) {
            $('#mytable').DataTable();
        });
    }

</script>
@if (TempData["Message"] != null)
{
    <script type="text/javascript">
        window.onload = function () {
            alert('@TempData["Message"]');
            window.location.href = "/DematMaster/Index";
        };
    </script>
}
<script src="~/AngularDataFunction/AngularDataFunction.js"></script>
<script src="~/AngScripts/DematList.js"></script>

IRecordweb/Views/DematMaster/SaveDemat.cshtml
@model IRecordweb.Models.DEMAT

@{
    ViewBag.Title = "SaveDemat";
}



<div class="display_adds_parent">
    <div class="display_adds_view_box display_adds_2_col">

        <div class="col-12">
            <div class="page-title-box d-flex align-items-center justify-content-between">
                <h1 class="mb-0">Demat Master</h1>

                <div class="page-title-right">
                    @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-dark" })
                </div>

            </div>
        </div>


        <div class="card">
            <div class="card-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="row form_2">
                        @*<h4>Demat</h4>*@
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="col-sm-12 col-md-6 mb-3 d-flex">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="w-100">
                                @Html.ListBoxFor(model => model.SelectedMultiDemate, this.ViewBag.DemateList as SelectList, new { id = "MultiDemate", @multiple = "multiple", @class = "selectCountry show-tick form-control input-md" })

                            </div>
                        </div>

                        <div class="col-sm-12 col-md-6 mb-3 d-flex">
                            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="w-100">
                                <div class="checkbox">
                                    @Html.CheckBoxFor(model => model.Active, htmlAttributes: new { @Checked = true })
                                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="col-md-12 text-center mt-3">
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>
                    </div>
                }
            </div>
        </div>

    </div>
    <div class="display_adds display_adds_right text-center">
        <div class="mobile_adds mb-3">
            <img src="https://via.placeholder.com/970x90.png/007BFF/FFFFFF?text=Irecord+Ads" alt="" />
        </div>
        <div class="desktop_adds">
            <img src="https://via.placeholder.com/160x601.png/007BFF/FFFFFF?text=Irecord+Ads" alt="" />
        </div>
    </div>
</div>

@section Scripts {

    @*For Duplicate Name Validate*@

    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/select2.min.js"></script>
    <link href="~/css/select2.min.css" rel="stylesheet" />

    <script>

        $(document).ready(function () {
            $("#MultiDemate").focus();

            $('#MultiDemate').select2();
        });
    </script>

    @if (ViewBag.Message != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert('@ViewBag.Message');
            };
        </script>
    }
}