IRecordweb/Controllers/ScriptMasterDownloadController.cs
using BAL;
using IRecordweb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace IRecordweb.Controllers
    {
    public class ScriptMasterDownloadController : Controller
        {
        DAL.Master obj = new DAL.Master();
        MType mtype = new MType();
        // GET: ScriptMasterDownload
        public ActionResult Index()
            {
            return View();

            }
       
        [HttpGet]
        public ActionResult ScriptUpload(string Upload, string Download, HttpPostedFileBase FilePath , int? Page)
            {
            ScriptUploadDownload _Script = new ScriptUploadDownload();      
           
            _Script.scripdata = obj.SelectallScriptdata();
           // data.ToList().ToPagedList(10, 10);

             ViewBag.InvestmentType = new SelectList(obj.BindInvenstmentType(mtype).ToList(), dataValueField: "TypeId", dataTextField: "Name");
            return View(_Script);
          //  return View(data.ToPagedList(1, 10));
            }

        [HttpPost]
        public ActionResult ScriptUpload(ScriptUploadDownload _Script, string Download, string Upload, string Save, HttpPostedFileBase FilePath, IRecordweb.Models.ImportExcel import)
            {

            if (!string.IsNullOrEmpty(Download))
                {
                // _Script.scripdata = obj.SelectallScriptdata();
                _Script.scripdata = obj.InsertDownloadScriptMaster(_Script);
                //obj.DownloadScriptData(_Script, FilePath);
                }
            else if (!string.IsNullOrEmpty(Upload))
                {
                if (_Script.FilePath.ContentLength > 0)
                    {                   
                        _Script.scripdata = obj.UploadData(_Script, FilePath);
                    }
                }
            else if (!string.IsNullOrEmpty(Save))
                {
                _Script.scripdata = obj.InsertBulkScriptMaster(_Script, FilePath);
                ViewBag.Message = "Data Upload Successfully";
                }

            ViewBag.InvestmentType = new SelectList(obj.BindInvenstmentType(mtype).ToList(), dataValueField: "TypeId", dataTextField: "Name");
            return View(_Script);
            }
        [HttpGet]
        public ActionResult DownloadScript(string Upload, HttpPostedFileBase FilePath)
            {
            ScriptUploadDownload _Script = new ScriptUploadDownload();
           
            _Script.scripdata = obj.UploadData(_Script, FilePath);
            return View(_Script);
            }


       [HttpPost]
        public ActionResult DownloadScript(ScriptUploadDownload _Script, string Upload, HttpPostedFileBase FilePath)
            {
            if (!string.IsNullOrEmpty(Upload))
                {
                if (_Script.FilePath.ContentLength > 0)
                    {
                    _Script.scripdata = obj.UploadData(_Script, FilePath);
                    ViewBag.Message = "Saved Successfully";
                    }
                }
            return View(_Script);
            }

        }
    }

IRecordweb/Views/ScriptMasterDownload/DownloadScript.cshtml
@model IEnumerable<BAL.ScriptUploadDownload>

@{
    ViewBag.Title = "DownloadScript";
}

<h2>DownloadScript</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("DownloadScript", "ScriptMasterDownload", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ScriptName)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.BSECode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NSECode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IndustryID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GroupName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InvestmentType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsMcx)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsCurrency)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsNcdx)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsFO)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.FaceValue)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.ISIN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MutualFundID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Active)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TypeId)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model.scripdatalist)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ScriptName)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.BSECode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NSECode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IndustryID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GroupName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.InvestmentType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsMcx)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsCurrency)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsNcdx)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsFO)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.FaceValue)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.ISIN)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MutualFundID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Active)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedBy)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ModifiedBy)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ModifiedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TypeId)
        </td>*@
        @*<td>
            @Html.ActionLink("Edit", "Edit", new { id = item.ScriptID }) |
            @Html.ActionLink("Details", "Details", new { id = item.ScriptID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.ScriptID })
        </td>*@
    </tr>
    }

</table>
    }

IRecordweb/Views/ScriptMasterDownload/ScriptUpload.cshtml
@model BAL.ScriptUploadDownload


@using PagedList;
@using PagedList.Mvc;

@{
    ViewBag.Title = "ScriptUpload";
}

@section Scripts {
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>


    @if (ViewBag.Message != null)
        {
        <script type="text/javascript">
            window.onload = function () {
                alert('@ViewBag.Message');
            };
        </script>
        }
}
<script>
    function DisplayVal() {
      
        var Investment = document.getElementById('InvestmentType');
        var Exchange = document.getElementById('Exchange');
        if (document.getElementById('InvestmentType').value == 'Equity')
        {
            document.getElementById('Exchange').style.visibility = 'visible';
        }
        else {
        
            document.getElementById('Exchange').style.visibility = 'hidden';
        }
    }



    function leaveChange() {
        if (document.getElementById("leave").value != "100") {
            document.getElementById("message").innerHTML = "Common message";
        }
        else {
            document.getElementById("message").innerHTML = "Having a Baby!!";
        }
    }
</script>
<script>
    function UploadData() {
        var integerInput = document.getElementById("Upload");
        var integer = Number(integerInput.value);
        if (Upload.click()) {
            $('#uploadlist').visible = true;
            $('#DownloadData').visible = false;
        }

    }
</script>

<style>
    .file {
        margin-top: 8px;
        padding-left: 53px;
    }
</style>

<h2>Script Master Upload</h2>

@using (Html.BeginForm("ScriptUpload", "ScriptMasterDownload", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <table>
                <tr>
                    <td class="form-group">
                        @Html.LabelFor(model => model.InvestmentType, htmlAttributes: new { @class = "control-label col-md-12" })
                    </td>
                    <td>
                        <div class="col-md-20">
                            @*@Html.DropDownListFor(model => model.InvestmentType, ViewBag.InvestmentType as SelectList, "Select Investment Type", htmlAttributes: new { @class = "form-control" })*@
                            <select id="InvestmentType" name="InvestmentType" onchange="DisplayVal()" class="form-control">
                                <option value="1">Equity</option>
                                <option value="2">Mutual Fund</option>
                            </select>
                            @Html.ValidationMessageFor(model => model.InvestmentType, "", new { @class = "text-danger" })
                        </div>
                    </td>
                    <td class="col col-md-2">&nbsp;</td>

                    <td>
                        <div id="Exchange">
                            @Html.LabelFor(model => model.Exchange, htmlAttributes: new { @class = "control-label col-md-20" })

                            @*<div class="col-md-20">*@
                            BSE &nbsp;  @Html.RadioButtonFor(model => model.Exchange, "BSE", htmlAttributes: new { @checked = true }) &nbsp;
                                NSE &nbsp; @Html.RadioButtonFor(model => model.Exchange, "NSE") &nbsp;
                                @*</div>*@
                            @*BSE  <input type="radio" value="rdsbe" checked />
                            NSE <input type="radio" value="rdnse" />*@
                            @Html.ValidationMessageFor(model => model.Exchange, "", new { @class = "text-danger" })
                        </div>
                    </td>

                </tr>
            </table>
        </div>
        <div class="form-group">
            <table>
                <tr>
                    <td class="form-group">
                        @Html.Label("Select File", htmlAttributes: new { @class = "control-label col-md-12" })
                    </td>
                    <td>
                        <div class="col-md-20">
                            @Html.TextBoxFor(m => m.FilePath, htmlAttributes: new { @class = "form-control", type = "file", value = "FilePath" })
                            @*<input type="file" name="FilePath" required />*@
                        </div>
                    </td>
                    <td>&nbsp;</td>
                    <td>
                        <input type="submit" value="Upload" name="Upload" id="Upload" class="btn btn-primary" onclick="UploadData();" />
                    </td>
                    <td>&nbsp;</td>
                    <td>
                        <input type="submit" value="OK" class="btn btn-success" />
                    </td>
                    <td>&nbsp;</td>
                    <td>
                        <input type="submit" value="Download Script Master" name="Download" class="btn btn-danger" id="Download" />
                    </td>
                </tr>

            </table>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" name="Save" id="Save" class="btn btn-success" />
            </div>
        </div>
    </div>



    @* New Code Added for grid *@

    <div id="DownloadData">
        <table class="table table-striped table-hover">
            <thead class="row">
                <tr>

                    <th>
                        @Html.DisplayNameFor(model => model.ScriptName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.BSECode)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.NSECode)
                    <th>
                        @Html.DisplayNameFor(model => model.GroupName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FaceValue)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ISIN)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.InvestmentType)
                    </th>
                </tr>
            </thead>

            @foreach (var item in Model.scripdata)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ScriptName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BSECode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NSECode)
                        @* @Html.DropDownListFor(modelItem => item.MemberName, ViewBag.MemberName as SelectList, "Select Member")*@
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GroupName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FaceValue)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ISIN)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.InvestmentType)
                    </td>

                </tr>
                }
        </table>
    </div>
    }

@*@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))*@

@*<div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@