IRecordweb/Controllers/MutualFundCategoryController.cs
using BAL;
using IRecordweb.Models;
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace IRecordweb.Controllers
{
    //[Authorize]
    public class MutualFundCategoryController : Controller
    {
        string URL = ConfigurationManager.AppSettings["ScreenURL"];
        string BasicAuth = ConfigurationManager.AppSettings["Authorization"];
        // GET: MutualFundCategory
        public ActionResult Index()
        {
            var ID = Session["UserID"];
            System.Net.ServicePointManager.SecurityProtocol =SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;System.Net.ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };
            var client = new RestClient(URL + "api/Master/FUNDCATEGORYMASTER?DBAction=ViewByUserId&ID=" + ID);
            client.Timeout = -1;
            var request = new RestRequest(Method.POST);
            request.AddHeader("Authorization", BasicAuth);
            request.AddHeader("Content-Type", "application/json");
            IRestResponse response = client.Execute(request);
            Console.WriteLine(response.Content);
            DataSet data = JsonConvert.DeserializeObject<DataSet>(response.Content);
            List<FUNDCATEGORY> list = new List<FUNDCATEGORY>();
            foreach (DataRow dr in data.Tables[0].Rows)
                {
                FUNDCATEGORY item = new FUNDCATEGORY();
                item.MutualFundCategoryID = Convert.ToInt32(dr["MutualFundCategoryID"].ToString());
                item.Code = dr["Code"].ToString();
                item.Name = dr["Name"].ToString();
                item.Active = Convert.ToBoolean(dr["Active"].ToString());
                item.CreatedDate = Convert.ToDateTime(dr["CreatedDate"].ToString());

                list.Add(item);
                }
            return View(list);
            }
        [HttpGet]
        public ActionResult SaveMutualFundCat()
            {    
            return View();
            }
        [HttpPost]
        public ActionResult SaveMutualFundCat(FUNDCATEGORY _FundCategory)
            {
            if (ModelState.IsValid)
                {
                var CreatedBy = Session["UserID"];
                FUNDCATEGORY objdata = new FUNDCATEGORY();
                objdata.MutualFundCategoryID = _FundCategory.MutualFundCategoryID;
                objdata.Name = _FundCategory.Name;
                objdata.Active = _FundCategory.Active;
                objdata.CreatedBy = Convert.ToInt32(CreatedBy.ToString());
                var json = new JavaScriptSerializer().Serialize(objdata);
                System.Net.ServicePointManager.SecurityProtocol =SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;System.Net.ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };
                var client = new RestClient(URL + "api/Master/FUNDCATEGORYMASTER?DBAction=Insert&ID=0");
                client.Timeout = -1;
                var request = new RestRequest(Method.POST);
                request.AddHeader("Authorization", BasicAuth);
                request.AddHeader("Content-Type", "application/json");
                request.AddParameter("application/json", json.ToString(), ParameterType.RequestBody);
                IRestResponse response = client.Execute(request);
                Console.WriteLine(response.Content);
                DataSet data = JsonConvert.DeserializeObject<DataSet>(response.Content);
                foreach (DataRow dr in data.Tables[0].Rows)
                    {
                    FUNDCATEGORY item = new FUNDCATEGORY();
                    item.Code = dr["Code"].ToString();
                    item.Message = dr["Message"].ToString();
                    if (item.Code == "200")
                        {
                        ViewBag.Message = item.Message;
                        return RedirectToAction("Index");
                        }
                    else
                        {
                        ViewBag.Message = item.Message;
                        return View();
                        }
                    }
                }
            return RedirectToAction("Index");
            }

        [HttpGet]
        public ActionResult MutualFundCatDetails(int id)
            {
            System.Net.ServicePointManager.SecurityProtocol =SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;System.Net.ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };
            var client = new RestClient(URL + "api/Master/FUNDCATEGORYMASTER?DBAction=ViewById&ID="+ id);
            client.Timeout = -1;
            var request = new RestRequest(Method.POST);
            request.AddHeader("Authorization", BasicAuth);
            request.AddHeader("Content-Type", "application/json");
            IRestResponse response = client.Execute(request);
            Console.WriteLine(response.Content);
            FundCategoryModel.Rootobject obj = new FundCategoryModel.Rootobject();
            obj = JsonConvert.DeserializeObject<FundCategoryModel.Rootobject>(response.Content.ToString());
            FUNDCATEGORY FundCategory = new FUNDCATEGORY();
            foreach (FundCategoryModel.Datum dr in obj.Data)
                {
                FundCategory.MutualFundCategoryID = Convert.ToInt32(dr.MutualFundCategoryID.ToString());
                FundCategory.Code = dr.Code.ToString();
                FundCategory.Name = dr.Name.ToString();
                FundCategory.Active = Convert.ToBoolean(dr.Active.ToString());
                FundCategory.CreatedDate = Convert.ToDateTime(dr.CreatedDate.ToString());
                ViewData["FundCatModel"] = FundCategory;
                }
            var data = ViewData["FundCatModel"];
            return View(data);
            }
        [HttpGet]
        public ActionResult MutualFundCatUpdate(int id)
            {
            System.Net.ServicePointManager.SecurityProtocol =SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;System.Net.ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };
            var client = new RestClient(URL + "api/Master/FUNDCATEGORYMASTER?DBAction=ViewById&ID=" + id);
            client.Timeout = -1;
            var request = new RestRequest(Method.POST);
            request.AddHeader("Authorization", BasicAuth);
            request.AddHeader("Content-Type", "application/json");
            IRestResponse response = client.Execute(request);
            Console.WriteLine(response.Content);
            FundCategoryModel.Rootobject obj = new FundCategoryModel.Rootobject();
            obj = JsonConvert.DeserializeObject<FundCategoryModel.Rootobject>(response.Content.ToString());
            FUNDCATEGORY FundCategory = new FUNDCATEGORY();
            foreach (FundCategoryModel.Datum dr in obj.Data)
                {
                FundCategory.MutualFundCategoryID = Convert.ToInt32(dr.MutualFundCategoryID.ToString());
                FundCategory.Code = dr.Code.ToString();
                FundCategory.Name = dr.Name.ToString();
                FundCategory.Active = Convert.ToBoolean(dr.Active.ToString());
                FundCategory.CreatedDate = Convert.ToDateTime(dr.CreatedDate.ToString());
                ViewData["FundCatModel"] = FundCategory;
                }
            var data = ViewData["FundCatModel"];
            return View(data);
            }
        [HttpPost]
        public ActionResult MutualFundCatUpdate(FUNDCATEGORY MFCat,  int id)
            {
            if(!string.IsNullOrWhiteSpace(MFCat.Name))
                {
                var CreatedBy = Session["UserID"];
                FUNDCATEGORY objdata = new FUNDCATEGORY();
                objdata.MutualFundCategoryID = id;
                objdata.Name = MFCat.Name;
                objdata.Active = MFCat.Active;
                objdata.ModifiedBy = Convert.ToInt32(CreatedBy.ToString());
                var json = new JavaScriptSerializer().Serialize(objdata);
                System.Net.ServicePointManager.SecurityProtocol =SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;System.Net.ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };
                var client = new RestClient(URL + "api/Master/FUNDCATEGORYMASTER?DBAction=Update&ID="+ id);
                client.Timeout = -1;
                var request = new RestRequest(Method.POST);
                request.AddHeader("Authorization", BasicAuth);
                request.AddHeader("Content-Type", "application/json");
                request.AddParameter("application/json", json.ToString(), ParameterType.RequestBody);
                IRestResponse response = client.Execute(request);
                Console.WriteLine(response.Content);
                }
            return RedirectToAction("Index");
            }
        [HttpGet]
        public ActionResult MutualFundCatDelete(int id)
            {
            System.Net.ServicePointManager.SecurityProtocol =SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;System.Net.ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };
            var client = new RestClient(URL + "api/Master/FUNDCATEGORYMASTER?DBAction=ViewById&ID=" + id);
            client.Timeout = -1;
            var request = new RestRequest(Method.POST);
            request.AddHeader("Authorization", BasicAuth);
            request.AddHeader("Content-Type", "application/json");
            IRestResponse response = client.Execute(request);
            Console.WriteLine(response.Content);

IRecordweb/Views/MutualFundCategory/Index.cshtml
@model IEnumerable<IRecordweb.Models.FUNDCATEGORY>

@{
    ViewBag.Title = "Index";
}

<style>
    .isdisabled {
        color: currentColor;
        cursor: not-allowed;
        opacity: 0.5;
        text-decoration: none;
        pointer-events: none;
    }
</style>

<div class="display_ad display_ad_top text-center mb-3">
    <img src="https://via.placeholder.com/970x90.png/007BFF/FFFFFF?text=Irecord+Ads" alt="" />
</div>

<div class="col-12">
    <div class="page-title-box d-flex align-items-center justify-content-between">
        <h1 class="mb-0">Mutual Fund Category Master</h1>

        <div class="page-title-right">
            <input type="submit" class="btn btn-primary add-on" value="Add Fund Category" onclick="location.href='@Url.Action("SaveMutualFundCat", "MutualFundCategory")'" />
            @*@if (Session["RoleId"] != null)
            {
                if (Session["RoleName"].ToString() == "ADMIN" || Session["RoleName"].ToString() == "CA" || Session["RoleName"].ToString() == "INVESTOR" || Session["RoleName"].ToString() == "ACCOUNTANT" || Session["RoleName"].ToString() == "ADVISOR")
                {
                    <input type="submit" class="btn btn-primary add-on" value="Add Fund Category" onclick="location.href='@Url.Action("SaveMutualFundCat", "MutualFundCategory")'" />
                }
                else if (Session["RoleName"].ToString() == "OPERATOR")
                {
                    <input type="submit" class="btn btn-primary disabled isdisabled" value="Add Fund Category" onclick="location.href='@Url.Action("SaveMutualFundCat", "MutualFundCategory")'" />
                }
            }*@
        </div>

    </div>
</div>




<div class="card mutualfund_cate_master_par">
    <div class="card-body">
        <div class="row form_2">

            <table class="table table-hover table-bordered mb-0">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Code)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Active)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CreatedDate)
                    </th>
                    <th>
                        @Html.DisplayName("Action")
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    string Active = item.Active == true ? "Active" : "Inactive";
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Code)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Active)
                    </td>
                    <td>
                        @Html.DisplayNameFor(model => model.CreatedDate)
                    </td>
                    <td>
                        @Html.ActionLink(" ", "MutualFundCatUpdate", new { id = item.MutualFundCategoryID }, new { @class = "px-2 btn btn-outline-primary las la-pencil-alt font-size-18" })
                        @Html.ActionLink(" ", "MutualFundCatDetails", new { id = item.MutualFundCategoryID }, new { @class = "px-2 btn btn-outline-primary las la-search font-size-18" })
                        @Html.ActionLink(" ", "MutualFundCatDelete", new { id = item.MutualFundCategoryID }, new { @class = "px-2 btn btn-outline-danger las la-trash-alt font-size-18" })
                    </td>
                    @*@if (Session["RoleId"] != null)
                    {
                        if (Session["RoleName"].ToString() == "ADMIN" || Session["RoleName"].ToString() == "CA" || Session["RoleName"].ToString() == "INVESTOR" || Session["RoleName"].ToString() == "ACCOUNTANT" || Session["RoleName"].ToString() == "ADVISOR")
                        {

                        }
                        else
                        {
                            <td>
                                @Html.ActionLink(" ", "MutualFundCatUpdate", new { id = item.MutualFundCategoryID }, new { @class = "isdisabled px-2 btn btn-outline-primary las la-pencil-alt font-size-18" })
                                @if (Session["RoleName"].ToString() == "OPERATOR")
                                {
                                    @Html.ActionLink(" ", "MutualFundCatDetails", new { id = item.MutualFundCategoryID }, new { @class = "px-2 btn btn-outline-primary las la-search font-size-18" })
                                }
                                @Html.ActionLink("Delete", "MutualFundCatDelete", new { id = item.MutualFundCategoryID }, new { @class = "isdisabled px-2 btn btn-outline-danger las la-trash-alt font-size-18" })
                            </td>
                        }
                    }*@
                </tr>
                }

            </table>
        </div>
    </div>
</div>

IRecordweb/Views/MutualFundCategory/MutualFundCatDelete.cshtml
@model IRecordweb.Models.FUNDCATEGORY
@{
    ViewBag.Title = "MutualFundCatDelete";
}

<div class="display_ad_parent">
    <div class="display_ad_view_box">

        <div class="col-12">
            <div class="page-title-box d-flex align-items-center justify-content-between">
                <h1 class="mb-0">Mutual Fund Category Master</h1>

                <div class="page-title-right">
                    @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-dark ml-1" })
                </div>

            </div>
        </div>

        @{
            bool status = Model.Active;
            string Active = status == true ? "Active" : "Inanctive";
        }

        <div class="card mutualfund_cate_master_par">
            <div class="card-body">
                <div class="row form_2">
                    <div class="col-sm-12 col-md-6 mb-3 d-flex">
                        <label class="mb-0">
                            @Html.DisplayNameFor(model => model.Name)
                        </label>
                        <span class="form-control">@Html.DisplayFor(model => model.Name)</span>
                    </div>

                    <div class="col-sm-12 col-md-6 mb-3 d-flex">
                        <label class="mb-0">
                            @Html.DisplayNameFor(model => model.Code)
                        </label>
                        <span class="form-control">@Html.DisplayFor(model => model.Code)</span>
                    </div>

                    <div class="col-sm-12 col-md-6 mb-3 d-flex">
                        <label class="mb-0">
                            @Html.DisplayNameFor(model => model.Active)
                        </label>
                        <span class="form-control">@Html.DisplayFor(model => Active)</span>
                    </div>

                    <div class="col-sm-12 col-md-6 mb-3 d-flex">
                        <label class="mb-0">
                            @Html.DisplayNameFor(model => model.CreatedDate)
                        </label>
                        <span class="form-control">@Html.DisplayFor(model => model.CreatedDate)</span>
                    </div>

                    <div class="col-sm-12 text-center mt-3">
                        <input type="button" value="Delete" class="btn btn-danger" data-bs-target="#myModal" data-bs-toggle="modal" />
                    </div>
                </div>
            </div>
        </div>

        @*@using (Html.BeginForm()) {
            @Html.AntiForgeryToken()*@

        @*}*@

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="modal fade" id="myModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-md">
                    <div class="modal-content">

                        <!-- Modal Header -->
                        <div class="modal-header">
                            <h4 class="modal-title">Delete Mutual Fund Category Master</h4>
                            <div class="btn-close" data-bs-dismiss="modal"></div>
                        </div>

                        <!-- Modal body -->
                        <div class="modal-body">
                            Are you sure you want to delete this?
                        </div>

                        <!-- Modal footer -->
                        <div class="modal-footer">
                            <input type="submit" value="OK" name="OK" class="btn btn-danger">
                            <button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button>
                        </div>

                    </div>
                </div>
            </div>
        }

    </div>
    <div class="display_ad display_ad_right text-center">
        <div class="mobile_ad mb-3">
            <img src="https://via.placeholder.com/970x90.png/007BFF/FFFFFF?text=Irecord+Ads" alt="" />
        </div>
        <div class="desktop_ad">
            <img src="https://via.placeholder.com/160x601.png/007BFF/FFFFFF?text=Irecord+Ads" alt="" />
        </div>
    </div>
</div>

IRecordweb/Views/MutualFundCategory/MutualFundCatDetails.cshtml
@model IRecordweb.Models.FUNDCATEGORY

    @{
        ViewBag.Title = "MutualFundCatDetails";
    }
    @*<style>
            .isdisabled {
                color: currentColor;
                cursor: not-allowed;
                opacity: 0.5;
                text-decoration: none;
                pointer-events: none;
            }
        </style>*@

    <div class="display_ad_parent">
        <div class="display_ad_view_box">

            <div class="col-12">
                <div class="page-title-box d-flex align-items-center justify-content-between">
                    <h1 class="mb-0">Mutual Fund Category Master</h1>

                    <div class="page-title-right">
                        @if (Session["RoleId"] != null)
                            {
                            if (Session["RoleName"].ToString() == "ADMIN" || Session["RoleName"].ToString() == "ACCOUNTANT" || Session["RoleName"].ToString() == "INVESTOR" || Session["RoleName"].ToString() == "MEMBER" || Session["RoleName"].ToString() == "ADVISOR")
                                {
                                @Html.ActionLink("Edit", "MutualFundCatUpdate", new { id = Model.MutualFundCategoryID }, new { @class = "btn btn-primary" })
                                }
                            else
                                {
                                @Html.ActionLink("Edit", "MutualFundCatUpdate", new { id = Model.MutualFundCategoryID }, new { @class = "isdisabled btn btn-primary disabled" })
                                }
                            }
                        @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-dark ml-1" })
                    </div>

                </div>
            </div>

            @{
                bool status = Model.Active;
                string Active = status == true ? "Active" : "Inanctive";
            }

            <div class="card mutualfund_cate_master_par">
                <div class="card-body">
                    <div class="row form_2">
                        <div class="col-sm-12 col-md-6 mb-3 d-flex">
                            <label class="mb-0">
                                @Html.DisplayNameFor(model => model.Name)
                            </label>
                            <span class="form-control">@Html.DisplayFor(model => model.Name)</span>
                        </div>

                        <div class="col-sm-12 col-md-6 mb-3 d-flex">
                            <label class="mb-0">
                                @Html.DisplayNameFor(model => model.Code)
                            </label>
                            <span class="form-control">@Html.DisplayFor(model => model.Code)</span>
                        </div>

                        <div class="col-sm-12 col-md-6 mb-3 d-flex">
                            <label class="mb-0">
                                @Html.DisplayNameFor(model => model.Active)
                            </label>
                            <span class="form-control">@Html.DisplayFor(model => Active)</span>
                        </div>

                        <div class="col-sm-12 col-md-6 mb-3 d-flex">
                            <label class="mb-0">
                                @Html.DisplayNameFor(model => model.CreatedDate)
                            </label>
                            <span class="form-control">@Html.DisplayFor(model => model.CreatedDate)</span>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="display_ad display_ad_right text-center">
            <div class="mobile_ad mb-3">
                <img src="https://via.placeholder.com/970x90.png/007BFF/FFFFFF?text=Irecord+Ads" alt="" />
            </div>
            <div class="desktop_ad">
                <img src="https://via.placeholder.com/160x601.png/007BFF/FFFFFF?text=Irecord+Ads" alt="" />
            </div>
        </div>
    </div>

IRecordweb/Views/MutualFundCategory/MutualFundCatDetails1.cshtml
@model BAL.MutualFundCategory

@{
    ViewBag.Title = "MutualFundCatDetails";
}

<h1>Mutual Fund Category Master</h1>

@{
    bool status = Model.Active;
    string Active = status == true ? "Active" : "Inanctive";
}

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "MutualFundCatUpdate", new { id = Model.MutualFundCategoryID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

IRecordweb/Views/MutualFundCategory/MutualFundCatUpdate.cshtml
@model IRecordweb.Models.FUNDCATEGORY

@{
    ViewBag.Title = "MutualFundCatUpdate";
}

<div class="display_ad_parent">
    <div class="display_ad_view_box">

        <div class="col-12">
            <div class="page-title-box d-flex align-items-center justify-content-between">
                <h1 class="mb-0">Mutual Fund Category Master</h1>

                <div class="page-title-right">
                    @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-dark" })
                </div>

            </div>
        </div>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="card mutualfund_cate_master_par">
                <div class="card-body">
                    <div class="row form_2">

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.MutualFundCategoryID)

                        <div class="col-sm-12 col-md-6 mb-3 d-flex">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="w-100">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="col-sm-12 col-md-6 mb-3 d-flex">
                            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="w-100">
                                <div class="checkbox">
                                    @Html.EditorFor(model => model.Active)
                                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="col-md-12 text-center mt-3">
                            <input type="button" value="Update" class="btn btn-primary" data-bs-target="#myModal" data-bs-toggle="modal" />
                        </div>
                    </div>
                </div>
            </div>

            <div class="modal fade" id="myModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-md">
                    <div class="modal-content">

                        <!-- Modal Header -->
                        <div class="modal-header">
                            <h4 class="modal-title">Update Mutual Fund Category Master </h4>
                            <div class="btn-close" data-bs-dismiss="modal"></div>
                        </div>

                        <!-- Modal body -->
                        <div class="modal-body">
                            Record Updated Successfully..!
                        </div>

                        <!-- Modal footer -->
                        <div class="modal-footer">
                            <input type="submit" value="OK" name="OK" class="btn btn-danger">
                            <button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button>
                        </div>

                    </div>
                </div>
            </div>
        }

    </div>
    <div class="display_ad display_ad_right text-center">
        <div class="mobile_ad mb-3">
            <img src="https://via.placeholder.com/970x90.png/007BFF/FFFFFF?text=Irecord+Ads" alt="" />
        </div>
        <div class="desktop_ad">
            <img src="https://via.placeholder.com/160x601.png/007BFF/FFFFFF?text=Irecord+Ads" alt="" />
        </div>
    </div>
</div>