IRecordweb/Controllers/BankStatementImportController.cs
using IRecordweb.Models;
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace IRecordweb.Controllers
{
    public class BankStatementImportController : Controller
    {
        private readonly string URL = ConfigurationManager.AppSettings["ScreenURL"];
        private readonly string BasicAuth = ConfigurationManager.AppSettings["Authorization"];
        private readonly string PdfConfig = ConfigurationManager.AppSettings["PdfConfig"];

        // GET: BankStatementImport
        public ActionResult Index()
        {
            ViewBag.BankNameId = new SelectList(GetBankFormat(), dataValueField: "ID", dataTextField: "NAME");
            ViewBag.BankConfig = new SelectList(GetBankFormatConfig(), dataValueField: "ID", dataTextField: "NAME");
            System.Web.HttpContext.Current.Session["member_code"] = "T0001";
            ViewData["asdf"] = "sdf";
            System.Web.HttpContext.Current.Session["year_code"] = "1120202021";
            return View();
        }
        public ActionResult ViewList()
        {
           

            return View();
        }
        [HttpGet]
        public JsonResult ViewFormate(string BankId)
        {
            string strConnString = ConfigurationManager.ConnectionStrings["IrecordwebConnection"].ConnectionString;
            SqlConnection con = new SqlConnection(strConnString);
            SqlCommand cmd = new SqlCommand
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[DBO].[SP_BANK_FORMATE_UTITLIY]"
            };
            cmd.Parameters.Add("@Action", SqlDbType.NVarChar).Value = "VIEWCONFIG";
            DataTable dtfin = Session["Dt_FinancialYear"] as DataTable;//Member Details(MemberId,FinancialYearUserID)
            string MemberCode = dtfin.Rows[0]["MemberId"].ToString();
            string FinancialYearCode = dtfin.Rows[0]["FinancialYearUserID"].ToString();
            string CreatedById = Session["UserID"].ToString();
            cmd.Parameters.Add("@MemberId", SqlDbType.Int).Value = MemberCode;
            cmd.Parameters.Add("@MemberYearId", SqlDbType.Int).Value = FinancialYearCode;
            cmd.Parameters.Add("@ID", SqlDbType.Int).Value = BankId;
            cmd.Connection = con;
            System.Data.DataTable DT = new System.Data.DataTable();
            try
            {
                con.Open();
                /////Only Use Case Of Mapping
                //string query = cmd.CommandText;
                //foreach (SqlParameter p in cmd.Parameters)
                //{
                //    query += " "+p.ParameterName+"="+p.Value.ToString()+"\n";
                //}
                using (SqlDataAdapter da = new SqlDataAdapter(cmd))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    da.Fill(DT);
                }
            }
            catch (Exception ex)
            {
                //throw ex;
            }
            finally
            {
                con.Close();
                con.Dispose();
            }
            List<MTYPE> list = new List<MTYPE>();
            foreach (DataRow dr in DT.Rows)
            {
                MTYPE item = new MTYPE();
                item.TypeId = Convert.ToInt32(dr["ID"].ToString());
                item.Name = dr["NAME"].ToString();
                list.Add(item);
            }
            return Json(list, JsonRequestBehavior.AllowGet);

        }


        [HttpPost]
        public ActionResult Index(BankStatement_Index_Model bank, HttpPostedFileBase fileupload)
        {
            // ViewBankStatement(bank, fileupload);
            Viewbankdata(bank, fileupload);
            return RedirectToAction("ViewBankStatement");
        }
        public JsonResult ReadAllBankData()
        {
            DataTable DT = Session["datadetails"] as DataTable;
            return Json(DataTableToJSON(DT), JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult ViewACCOUNT()
        {
            string strConnString = ConfigurationManager.ConnectionStrings["IrecordwebConnection"].ConnectionString;
            SqlConnection con = new SqlConnection(strConnString);
            SqlCommand cmd = new SqlCommand
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[DBO].[SP_BANKSTATEMENTDATA]"
            };
            cmd.Parameters.Add("@Action", SqlDbType.NVarChar).Value = "ViewAccount";
            DataTable dtfin = Session["Dt_FinancialYear"] as DataTable;//Member Details(MemberId,FinancialYearUserID)
            string MemberCode = dtfin.Rows[0]["MemberId"].ToString();
            string FinancialYearCode = dtfin.Rows[0]["FinancialYearUserID"].ToString();
            string CreatedById = Session["UserID"].ToString();
            cmd.Parameters.Add("@MemberID", SqlDbType.Int).Value = MemberCode;
            cmd.Parameters.Add("@FinancialYearMemberID", SqlDbType.Int).Value = FinancialYearCode;
            cmd.Connection = con;
            System.Data.DataTable DT = new System.Data.DataTable();
            try
            {
                con.Open();
                /////Only Use Case Of Mapping
                //string query = cmd.CommandText;
                //foreach (SqlParameter p in cmd.Parameters)
                //{
                //    query += " "+p.ParameterName+"="+p.Value.ToString()+"\n";
                //}
                using (SqlDataAdapter da = new SqlDataAdapter(cmd))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    da.Fill(DT);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                con.Close();
                con.Dispose();
            }
            return Json(DataTableToJSON(DT), JsonRequestBehavior.AllowGet);

        }
        public JsonResult ViewBnkSteUser()
        {
            string strConnString = ConfigurationManager.ConnectionStrings["IrecordwebConnection"].ConnectionString;
            SqlConnection con = new SqlConnection(strConnString);
            SqlCommand cmd = new SqlCommand
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[DBO].[SP_BANKSTATEMENTDATA]"
            };
            cmd.Parameters.Add("@Action", SqlDbType.NVarChar).Value = "View";
            DataTable dtfin = Session["Dt_FinancialYear"] as DataTable;//Member Details(MemberId,FinancialYearUserID)
            string MemberCode = dtfin.Rows[0]["MemberId"].ToString();
            string FinancialYearCode = dtfin.Rows[0]["FinancialYearUserID"].ToString();
            string CreatedById = Session["UserID"].ToString();
            cmd.Parameters.Add("@MemberID", SqlDbType.Int).Value = MemberCode;
            cmd.Parameters.Add("@FinancialYearMemberID", SqlDbType.Int).Value = FinancialYearCode;
            cmd.Connection = con;
            System.Data.DataTable DT = new System.Data.DataTable();
            try
            {
                con.Open();
                /////Only Use Case Of Mapping
                //string query = cmd.CommandText;
                //foreach (SqlParameter p in cmd.Parameters)
                //{
                //    query += " "+p.ParameterName+"="+p.Value.ToString()+"\n";
                //}
                using (SqlDataAdapter da = new SqlDataAdapter(cmd))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    da.Fill(DT);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                con.Close();
                con.Dispose();
            }
            return Json(DataTableToJSON(DT), JsonRequestBehavior.AllowGet);

        }
        public List<BankStatement_Index_Model> GetBankFormat()
        {
            DataTable dtfin = Session["Dt_FinancialYear"] as DataTable;//Member Details(MemberId,FinancialYearUserID)
            string MemberCode = dtfin.Rows[0]["MemberId"].ToString();
            string FinancialYearCode = dtfin.Rows[0]["FinancialYearUserID"].ToString();
            string CreatedById = Session["UserID"].ToString();


            string strConnString = ConfigurationManager.ConnectionStrings["IrecordwebConnection"].ConnectionString;
            SqlConnection con = new SqlConnection(strConnString);
            SqlCommand cmd = new SqlCommand
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[DBO].[SP_BANK_FORMATE_UTITLIY]"
            };
            cmd.Parameters.Add("@ACTION", SqlDbType.NVarChar).Value = "VIEWBANK";
            cmd.Parameters.Add("@MemberId", SqlDbType.Int).Value = MemberCode;
            cmd.Parameters.Add("@MemberYearId", SqlDbType.Int).Value = FinancialYearCode;

            cmd.Connection = con;
            System.Data.DataTable DT = new System.Data.DataTable();
            try
            {
                con.Open();
                /////Only Use Case Of Mapping
                //string query = cmd.CommandText;
                //foreach (SqlParameter p in cmd.Parameters)
                //{
                //    query += " "+p.ParameterName+"="+p.Value.ToString()+"\n";
                //}
                using (SqlDataAdapter da = new SqlDataAdapter(cmd))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    da.Fill(DT);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                con.Close();
                con.Dispose();

IRecordweb/Views/BankStatementImport/Index.cshtml
@model IRecordweb.Models.BankStatement_Index_Model
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="author" content="#">
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/line-awesome/1.3.0/line-awesome/css/line-awesome.min.css"> -->
<!-- <link rel="stylesheet" href="~/css/bootstrap.min.v4.css">
<link rel="stylesheet" href="~/css/select2.min.css">
<link rel="stylesheet" href="~/css/style.css"> -->
@*<script type="text/javascript" src="main.js"></script>*@
<style>
    /* footer.footer {
        margin-bottom: -568px;
    }

    .btn-primary {
        color: #fff;
        background-color: #5b73e8 !important;
        border-color: #5b73e8 !important;
    } */
</style>



<script src="~/AngScripts/angular.js"></script>
<script src="~/AngScripts/ngStorage.min.js"></script>
<script src="//angular-ui.github.io/bootstrap/ui-bootstrap-tpls-1.0.3.js"></script>


<div class="display_adds_parent">
    <div class="display_adds_view_box display_adds_2_col">

        <div class="col-12">
            <div class="page-title-box d-flex align-items-center justify-content-between">
                <h1 class="mb-0">Bank Statement</h1>

                @*<div class="page-title-right">
                        @Html.ActionLink("Back to List", "ViewList", "", new { @class = "btn btn-dark" })
                    </div>*@

            </div>
        </div>

        @using (Html.BeginForm("Index", "BankStatementImport", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {

            <div class="card member_master_par">
                <div class="card-body">
                    <div class="row form_2" id="data">
                        @*<h4>Member</h4>*@
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                        <div class="col-sm-12 col-md-6 mb-3 d-flex">
                            <label>
                                Bank Name
                            </label>
                            <div class="w-100">
                                @*ViewBag.BankNameId as SelectList*@
                                @Html.DropDownListFor(model => model.BankNameId, ViewBag.BankNameId as SelectList, "--Select Bank--", htmlAttributes: new { @class = "form-control select2" })
                                @Html.ValidationMessageFor(model => model.BankNameId, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="col-sm-12 col-md-6 mb-3 d-flex">
                            @Html.LabelFor(model => model.BankConfig, htmlAttributes: new { @class = "control-label" })
                            <div class="w-100">
                                @Html.DropDownListFor(model => model.BankConfig, null, "--Select Config--", htmlAttributes: new { @class = "form-control select2" })
                                @Html.ValidationMessageFor(model => model.BankConfig, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="col-sm-12 col-md-6 mb-3 d-flex">
                            @Html.LabelFor(model => model.FromDate, htmlAttributes: new { @class = "control-label" })
                            <div class="w-100">
                                @Html.EditorFor(model => model.FromDate, new { htmlAttributes = new { @class = "form-control", @readonly = true, @placeholder = "DD-MM-YYYY", @Value = Convert.ToDateTime(Session["FinFromDate"].ToString()).ToString("dd-MMM-yyyy") } })
                                @Html.ValidationMessageFor(model => model.FromDate, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="col-sm-12 col-md-6 mb-3 d-flex">
                            @Html.LabelFor(model => model.ToDate, htmlAttributes: new { @class = "control-label" })
                            <div class="w-100">
                                @Html.EditorFor(model => model.ToDate, new { htmlAttributes = new { @class = "form-control", @readonly = true, @placeholder = "DD-MM-YYYY", @Value = Convert.ToDateTime(Session["FinToDate"].ToString()).ToString("dd-MMM-yyyy") } })
                                @Html.ValidationMessageFor(model => model.ToDate, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-sm-12 col-md-6 mb-3 d-flex">
                            @Html.LabelFor(model => model.FileUpload, htmlAttributes: new { @class = "control-label" })
                            <div class="w-100">
                                @Html.TextBoxFor(model => model.FileUpload, htmlAttributes: new { @class = "form-control", type = "file", value = "FileName" })
                                @Html.ValidationMessageFor(model => model.FileUpload, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-sm-12 col-md-6 mb-3 d-flex">
                            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label" })
                            <div class="w-100">
                                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Password", autocomplete = "off" } })
                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                            </div>
                        </div>


                        <div class="col-sm-12 text-center mt-3">
                            <input type="submit" value="Reset" class="btn btn-secondary" />

                            <input type="submit" value="Save" name="Save" id="Save" class="btn btn-primary" onclick="Savebtn()" />
                        </div>
                    </div>
                </div>

            </div>
        }

    </div>
    <div class="display_adds display_adds_right text-center">
        <div class="mobile_adds mb-3">
            <img src="https://via.placeholder.com/970x90.png/007BFF/FFFFFF?text=Irecord+Ads" alt="" />
        </div>
        <div class="desktop_adds">
            <img src="https://via.placeholder.com/160x601.png/007BFF/FFFFFF?text=Irecord+Ads" alt="" />
        </div>
    </div>
</div>


@section Scripts {
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="../js/custom-script.js"></script>
    <script src="~/AngScripts/OpeningStock.js"></script>

    <script>
        $("#BankNameId").change(function () {

            var ddlCustomers = $("#BankConfig");
            ddlCustomers.empty();
            ddlCustomers.append("<option value=''>--Please Select--</option>");

            $.get("/BankStatementImport/ViewFormate", { BankId: $("#BankNameId").val() },
                function (data) {

                    $.each(data, function (index, row) {
                        ddlCustomers.append("<option value='" + row.TypeId + "'>" + row.Name + "</option>")
                    });
                });


            //$.ajax({    //create an ajax request to display.php
            //    type: "GET",
            //    url: "BankStatementImport/ViewFormate?BankId=" + $("#BankNameId").val(),
            //    dataType: "json",   //expect html to be returned
            //    success: function (response) {
            //        alert(response);
            //      //  $("#responsecontainer").html(response);
            //        //alert(response);
            //    }
            //});



            //$.ajax({
            //    type: "get", url: "BankStatementImport/ViewFormate?BankId=" + $("#BankNameId").val(), dataType: "json", contentType: "application/json", success: function (res) {
            //        $.each(res.d, function (data, value) {

            //            ddlCustomers.append($("<option></option>").val(value.ID).html(value.NAME));
            //        })
            //    }

            //});

        });


        // PopulateDropDownList();

        function PopulateDropDownList() {
            //Build an array containing Customer records.
            var customers = [
                { CustomerId: 1, Name: "John Hammond", Country: "United States" },
                { CustomerId: 2, Name: "Mudassar Khan", Country: "India" },
                { CustomerId: 3, Name: "Suzanne Mathews", Country: "France" },
                { CustomerId: 4, Name: "Robert Schidner", Country: "Russia" }
            ];

            var ddlCustomers = $("#BankConfig");
            ddlCustomers.empty();
            ddlCustomers.append("<option value=''>--Please Select--</option>");
            $(customers).each(function () {
                var option = $("<option />");

                //Set Customer Name in Text part.
                option.html(this.Name);

                //Set Customer CustomerId in Value part.
                option.val(this.CustomerId);

                //Add the Option element to DropDownList.
                ddlCustomers.append(option);
            });
        }
    </script>

    <script>
        $(document).ready(function () {
            $("#BankNameId").focus();
            $(".select2").select2({
                maximumSelectionLength: 3
            });
        });
    </script>
    <script>
       // $.noConflict();
        jQuery(document).ready(function ($) {

            var StartDate =@Session["FinFromDate"].ToString();
            var EndDate = @Session["FinToDate"].ToString();
           // alert(EndDate);
            $("#FromDate1").datepicker({
                dateFormat: "dd-mm-yy",
                minDate : StartDate,
                maxDate : EndDate,
                changeMonth: true,
                changeYear: true
            });
            $("#ToDate1").datepicker({
                dateFormat: "dd-mm-yy",
                minDate : StartDate,
                maxDate : EndDate,
                changeMonth: true,
                changeYear: true
            });
        });
    </script>
}

IRecordweb/Views/BankStatementImport/ViewBankStatement.cshtml
@{
    ViewBag.Title = "ViewBankStatement";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<h2>ViewBankStatement</h2>*@

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="~/css/bootstrap.min.v4.css" />
<link rel="stylesheet" href="~/css/line-awesome.min.css" />
<link rel="stylesheet" href="~/css/theme-color.css" />
<link rel="stylesheet" href="~/css/app.min.css" />
<link rel="stylesheet" href="~/css/custom-body.css" />
<script src="~/AngScripts/jquery-3.6.0.js"></script>
<script src="~/AngScripts/jquery-3.6.0.min.js"></script>
<script src="~/AngScripts/angular.js"></script>
<script src="~/AngScripts/ngStorage.min.js"></script>
<link rel="stylesheet" href="~/css/loader-1.css">

<div class="display_ad display_ad_top text-center mb-3">
    <img src="https://via.placeholder.com/970x90.png/007BFF/FFFFFF?text=Irecord+Ads" alt="" />
</div>
<div ng-app="myApp" ng-controller="myctrn" ng-init="PageLoad()">

    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="mb-0">Bank Statement</h4>

            <div class="page-title-right">
                <input type="submit" class="btn btn-success add-on" value="Add New" name="Add" onclick="location.href='@Url.Action("Index", "BankStatementImport")'" />

            </div>

        </div>
    </div>


    <div>
        <table class="table">
            <tr class="">
                <td>&nbsp;</td>
                <td><label class="control-label">Datewise Bill</label></td>

                <td><input type="text" id="BillDate" ng-model="search.Date" name="BillDate" class="form-control" /></td>

                <td>@*<input type="submit" value="Search" name="Search"  id="btnsearch" class="btn btn-info" />*@</td>

                <td>

                    <input type="button" value="{{btnsubmit}}" name="Save" id="Save" class="btn btn-success" ng-click="PostDeatils()" />


                </td>

            </tr>
        </table>
    </div>

    <div class="card fundfamily_par">
        <div class="card-body">
            <div class="table-responsive">
                <table style="
    display: block;
    overflow-x: auto;
    white-space: nowrap;
" class="table table-hover table-bordered mb-0">
                    <thead class="table-light">
                        <tr>


                            <th>

                            </th>
                            @*<th>
                                    Sr No
                                </th>*@
                            <th>
                                Date
                            </th>
                            <th>
                                Accounts
                            </th>
                            <th>
                                Cheque
                            </th>
                            <th>
                                Debit
                            </th>
                            <th>
                                Credit
                            </th>
                            <th>
                                Narration
                            </th>

                    </thead>
                    <tbody>

                        <tr ng-repeat="data in Info  | filter:search|orderBy:'Date'">
                            <td>
                                <a ng-click="FndeleteItems(data)" class="px-2 btn btn-outline-danger las la-trash-alt font-size-18"></a>

                            </td>
                            @*<td>
                                    {{$index+1}}
                                </td>*@

                            <td>
                                {{data.Date}}
                            </td>
                            <td>

                                <label ng-click="Ac_click(data)" style="color:{{data.Accounts_color}};"> {{data.Accounts}}</label>


                            </td>
                            <td>
                                {{data.Cheque}}

                            </td>
                            <td>
                                {{data.Debit}}

                            </td>


                            <td>
                                {{data.Credit}}

                            </td>
                            <td>
                                {{data.Narration}}

                            </td>

                        </tr>

                    </tbody>
                </table>
            </div>
        </div>

    </div>
    <a style="display:none" href="javascript:;" id="openModalButton" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#modal_ScriptMapping">
        <i class="la la-plus"></i>
    </a>
    <a style="display:none" href="javascript:;" id="openModalAccountAdd" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#modal_AddAccountMaster">
        <i class="la la-plus"></i>
    </a>
    <a style="display:none" href="javascript:;" id="openModalButtonAll" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#modal_ScriptAllMapping">
        <i class="la la-plus"></i>
    </a>
    <div class="modal fade" id="modal_ScriptMapping" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-xl">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Account Mapping</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row">

                        <div class="col-sm-2">Name of Ac:</div>
                        <div class="col-sm-2">{{ACMappingedit.Accounts}}</div>
                        <div class="col-sm-2">Mapping of Ac:</div>
                        <div class="col-sm-4">

                            <select id="ddlACCode" ng-model="ACMappingedit.ACcode" ng-options="v.ID as v.NAME for v in Acc" class="form-control">
                                <option ng-option value="Not Seleted">Not Seleted A/C</option>
                            </select>

                        </div>




                    </div>
                </div>
                <div class="modal-footer justify-content-center">

                    <button type="button" class="btn btn-secondary" ng-click="updateScriptmaster(ScpritMappingedit)" data-bs-dismiss="modal">Update</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modal_ScriptAllMapping" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-xl">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Account All Mapping</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <input type="button" class="btn btn-success add-on" ng-click="AddAccClick()" value="Add New Account" />
                        <table class="table">
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Name Of Script</th>
                                    <th scope="col">Map Script</th>
                                    @*<th scope="col">Action</th>*@
                                </tr>
                            </thead>
                            <tbody>
                                <tr ng-repeat="alldata in AllScriptMapModel track by $index">
                                    <th scope="row">{{$index+1}}</th>
                                    <td>{{alldata.Accounts}}</td>
                                    <td>
                                        <select ui-select2 id="ddlAllScriptCode" class="MySeleted2" ng-model="alldata.ACcode" ng-options="v.ID as v.NAME for v in Acc" class="form-control">
                                            <option ng-option value="Not Seleted">Not Seleted Account</option>
                                        </select>


                                    </td>
                                    @*<td><input type="button" class="btn btn-success add-on" ng-click="AddAccClick()" value="Add New Account" /></td>*@
                                </tr>

                            </tbody>
                        </table>




                    </div>
                </div>
                <div class="modal-footer justify-content-center">

                    <button type="button" class="btn btn-secondary" ng-click="SubmitAllScriptMap()" data-bs-dismiss="modal">Submit</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modal_AddAccountMaster" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-xl">
            <div class="modal-content">
                <div class="modal-header" style="
    background: #d4d4f1;
">
                    <h5 class="modal-title" id="staticBackdropLabel">Account Master</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" style="
    background: #d4d4f1;
">
                    <div class="row">

                        <iframe style="
    height: 1199px;
    width: 1199px;
" src="/AccountMaster/SaveAccountMaster?VarAction=WithOutLayout">
                          
                        </iframe>



                    </div>
                </div>
                <div style="
    background: #d4d4f1;
" class="modal-footer justify-content-center">

                    <button type="button" class="btn btn-secondary" ng-click="getAcc()" data-bs-dismiss="modal">Reload All Account</button>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {

    @*For Duplicate Name Validate*@

    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>



    @if (ViewBag.Message != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert('@ViewBag.Message');
            };
        </script>
    }
    <script src="~/AngularDataFunction/AngularDataFunction.js"></script>
    <script src="~/AngScripts/ViewBankStatementdetails.js"></script>
}